# This config file is for *DEVELOPMENT*
# Use merge/src/main/jib/app/config/application.yml or environment variables instead
# if you need to change the config in production environment.

spring:
    main:
        banner-mode: "off"
    datasource:
        url: jdbc:postgresql://localhost:5432/prism
        driver-class-name: org.postgresql.Driver
        username: prism
        password: prism
        hikari:
            maximum-pool-size: 2
            minimum-idle: 1

prism:
    bucket-name: prism-example-bucket
    prefix: ""
    merge-job-timeout: 600
    merged-object-size: 134217728  # 128MiB
    merge-batch-size: 2000
    downloader-threads: 4
    merger-threads: 2

logging:
    level:
        root: INFO
        com.cookpad.prism: DEBUG
        com.cookpad.prism.dao: INFO
        org.apache.parquet: WARN
        org.apache.hadoop: WARN
