# This config file is for *DEVELOPMENT*
# Edit stream/src/main/jib/app/config/application.yml or environment variables instead
# if you need to change the config in production environment.

spring:
    main:
        banner-mode: "off"
    datasource:
        url: jdbc:postgresql://localhost:5432/prism
        driver-class-name: org.postgresql.Driver
        username: prism
        password: prism
        hikari:
            maximum-pool-size: 2
            minimum-idle: 1

prism:
    bucket-name: prism-example-bucket
    prefix: ""
    queue-url: "https://sqs.ap-northeast-1.amazonaws.com/111111111111/prism-stream-events"
    #ignore-from-exclusive: "1900-01-01"
    #ignore-to-inclusive: "2000-01-01"

logging:
    level:
        root: INFO
        com.cookpad.prism: DEBUG
        com.cookpad.prism.dao: INFO
        org.apache.parquet: WARN
        org.apache.hadoop: WARN
